backend:
  image: backend
  container_name: testBackend
  restart: always
  ports:
    - "19300:19300"
  command: [/backend_wsl_linux, /config/dbconfig.json]
  volumes:
    - /home/pecho/go/bin/config:/config
